version: '3.1'
services:
  web:
    build: ./myapp
    image: mywebapp
    links:
     - mypostgres
    ports:
     - 8080:8080
  mypostgres:
    build: ./db
    image: mydb
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - 5432:5432
    restart: always
